---
title: "bilatsim"
author: "DVM Bishop and Paul Thompson"
date: "25/03/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggpubr") #for ggdensity function
require(tidyverse)
library(cowplot)
library(ggpubr)
library(knitr)
library(kableExtra)
library(matrixStats)
library(janitor)
library(propagate)
```

## Find optimum simulated data parameters to match for the real data


```{r simLI}

simLI_tab<-function(sim_type='B',npartic=1000,mymean=0,ntrial=15,TRT=0.7,SD_t1=0.5,SD_t2=0.8)
{
  #npartic=1000 #Large N participants simulated so can see distribution of laterality categories
  #nsess=2 #2 sessions
  
  mysim <- data.frame(matrix(NA,nrow=npartic,ncol=5))
  colnames(mysim)<-c('Subject','LI_t1','LI_t2','SE_t1','SE_t2') #,'lowCI','hiCI','Cat','Cat2')
  #ntrial <- 15 #n trials for each session
  thisrow<-0 #row counter for the data frame; incremented for each participant/session
  
  for (p in 1:npartic){
    mysim$Subject[p]<-p
    #It's really interesting to vary the value of mymean to see the effect!
    if(sim_type=='B')
    {
      #use runif to in effect throw a dice and flip sign on the effect for 50% of trials
      if (runif(1)<.5) {mymean <- mymean*-1}
    }
    else{mymean<-0}
    
    # PT: I have had to change the way that DB simulated the data to allow for the test-retest (TRT) correlation between the time points. The data is simulated in short form then change to long format and we can remove one loop and vectorise some calcs.
    myCorMat<-matrix(c(1,TRT,TRT,1),2,2,byrow=TRUE)
    mySigma <- propagate::cor2cov(myCorMat,var=c(SD_t1^2,SD_t1^2)) #convert correlation matrix to covariance matrix to allow jabberwocky dist to have different variance from 1 and allow unequal variance (possible, but unlikely).   
    
    LItrial <- MASS::mvrnorm(ntrial,c(mymean,mymean),Sigma=mySigma) #ntrial random normal deviates with mean mymean, SD = 1, and corr = TRT (see arguement inputs.
    
    mysim[p,c('LI_t1','LI_t2')] <- base::colMeans(LItrial)  #LI for that session is mean of individual trial LIs
    mysim[p,c('SE_t1','SE_t2')] <- matrixStats::colSds(LItrial)/sqrt(ntrial) #standard error for session LIs
  }

  mysim <- mysim %>% tidyr::gather(key='ref',value='value',-Subject) %>% tidyr::extract('ref',c('ref','Session'),"([[:alnum:]]+)_([[:alnum:]]+)")%>% tidyr::spread('ref','value') 
  
  
  mysim$lowCI <- with(mysim,LI - 1.96*SE) #95% CI lower bound for mean LI
  mysim$hiCI <- with(mysim,LI + 1.96*SE) #95% CI upper bound for mean LI
  #now categorise the mean LI for session as 1 = right, 2 = bilateral, 3 = left
  mysim$Cat<-2  #bilateral is the default
  
  for(j in 1:dim(mysim)[1]){
    
    if (mysim$hiCI[j]<0) {
      mysim$Cat[j] <-1} #R lateralised if top range of CI is below zero
    if (mysim$lowCI[j]>0) {
      mysim$Cat[j] <-3} #L lateralised if bottom range of CI is above zero
  }
  
  mysimCat2<-mysim %>%
    group_by(Subject) %>%
    summarise(Cat2 = paste(Cat, collapse=''))
  
  mysim$Cat2<-c(sapply(mysimCat2$Cat2, function(x) c(NA,x)))
  
  mysim$Cat2<-mysim$Cat2 %>% dplyr::recode_factor( '21' = "12", '32' = "23")
  mysim$Cat2 <- factor(mysim$Cat2, levels = c("11", "12", "22", "23","33"))
  
  mytab <- janitor::tabyl(mysim$Cat2, sort = TRUE) %>% dplyr::mutate(percent=round(percent*100,2)) %>% dplyr::select(3)
  
  #return(list(data = mysim, tab = mytab))
  return(mytab)
}


paramA <- expand.grid(sim_type='A',mymean=0, ntrial=c(15,20,30),TRT=c(0.6,0.7,0.8,0.9),SD_t1=c(0.5,0.75,0.8,1,1.5),SD_t2=c(0.5,0.75,0.8,1,1.5))

paramB <- expand.grid(sim_type='B',mymean=c(0,0.2,0.4), ntrial=c(15,20,30),TRT=c(0.6,0.7,0.8,0.9),SD_t1=c(0.5,0.75,0.8,1,1.5),SD_t2=c(0.5,0.75,0.8,1,1.5))


sims_A<-sims_B<-data.frame(iteration=rep(NA,300),cat11=rep(NA,300),cat12=rep(NA,300),cat22=rep(NA,300),cat23=rep(NA,300),cat33=rep(NA,300),'NA'=rep(NA,300))


for(i in 1:dim(paramA)[1])
{
  print(paste0("iteration ",i))
sims_A[i,] <- simLI_tab(sim_type=paramA[i,1],npartic=1000,mymean=paramA[i,2],ntrial=paramA[i,3],TRT=paramA[i,4],SD_t1=paramA[i,5],SD_t2=paramA[i,6])$percent
sims_B[i,] <- simLI_tab(sim_type=paramB[i,1],npartic=1000,mymean=paramB[i,2],ntrial=paramB[i,3],TRT=paramB[i,4],SD_t1=paramB[i,5],SD_t2=paramB[i,6])$percent
}

mysimfull<-rbind(sims_A,sims_B)
params<-rbind(paramA,paramB)
```




# Comparison with real data

Use A2 + Bangor data from Laterality_paper_analyses_Mar2020.rmd

```{r A2dataplus}
library(janitor)
myA2<-read.csv('all_LI_lat.csv')

myA2_left<-myA2[myA2$handedness=='L',]
myA2_right<-myA2[myA2$handedness=='R',]
#Focus on Jabberwocky as the least lateralised task

# get true percentages for left and right

trueleft <- tabyl(myA2_left$Jabber12, sort = TRUE) %>% mutate(percent=round(percent*100,2)) %>% select(3) 

trueright <- tabyl(myA2_right$Jabber12, sort = TRUE) %>% mutate(percent=round(percent*100,2)) %>% select(3) 

#FIND BEST SCENARIO MATCH TO REAL DATA
# Extract the differences between the percentages from each sim scenario and the real precentages. THen sum the absolute differences for each scenario and find the minimum for best fit. (similar to least squares-ish, but not regression!) 

#Calc diffs
diffsleft <- sweep(mysimfull,2,trueleft)
diffsright <- sweep(mysimfull,2,trueleft)

#convert to absolute values in each dataframe 
abs_diffs_left<-abs(diffsleft)
abs_diffs_right<-abs(diffsright)

# now, calc row sums of absolute values to give a value to guage minimum. This minimum indicates the smallest difference between precentages for all categories between simulated and real data. The smallest difference indicates the closest simulation setup to the real data...in theory :-)

abs_diffs_left$rowsum <- apply(abs_diffs_left,1,sum)
abs_diffs_right$rowsum <- apply(abs_diffs_right,1,sum)

left.sim.solution <- params[which.min(abs_diffs_left$rowsum),]
right.sim.solution <- params[which.min(abs_diffs_right$rowsum),]

```



```{r plots_left}
myA2_left2<-myA2_left[is.na(myA2_left$Jabber12)==FALSE,]
myA2_left2$Jabber12<-as.factor(myA2_left2$Jabber12)
myA2_left2$Jabber12<-recode_factor(myA2_left2$Jabber12, `22` = "bilateral both", `11` = "both lateralised", `33` = "both lateralised", `12`="bilateral in one session", `21`="bilateral in one session", `23`="bilateral in one session", `32`="bilateral in one session", `13`="opposite lateralisations", `31`="opposite lateralisations")
# Main plot
pmain <- ggplot(myA2_left2, aes(x = Jabber1, y = Jabber2, color = Jabber12))+
  geom_point()+ggpubr::color_palette("jco")+annotate('text',2,-2,label=paste0('r = ',round(cor(myA2_left$Jabber1,myA2_left$Jabber2,use='complete.obs'),2)))+theme_bw() + guides(color=guide_legend(title="Laterality class"))+ rremove("legend") 
# Marginal densities along x axis
xdens <- axis_canvas(pmain, axis = "x")+
  geom_density(data = myA2_left2, aes(x = Jabber1, fill = Jabber12),
               alpha = 0.7, size = 0.2)+
  ggpubr::fill_palette("jco")
# Marginal densities along y axis
# Need to set coord_flip = TRUE, if you plan to use coord_flip()
ydens <- axis_canvas(pmain, axis = "y", coord_flip = TRUE)+
  geom_density(data = myA2_left2, aes(x = Jabber2, fill = Jabber12),
               alpha = 0.7, size = 0.2)+
  coord_flip()+
  ggpubr::fill_palette("jco")
p1 <- insert_xaxis_grob(pmain, xdens, grid::unit(.2, "null"), position = "top")
p2<- insert_yaxis_grob(p1, ydens, grid::unit(.2, "null"), position = "right")
g1<-ggdraw(p2)

```


```{r plots_right}
myA2_right2<-myA2_right[is.na(myA2_right$Jabber12)==FALSE,]
myA2_right2$Jabber12<-as.factor(myA2_right2$Jabber12)
myA2_right2$Jabber12<-recode_factor(myA2_right2$Jabber12, `22` = "bilateral both", `11` = "both lateralised", `33` = "both lateralised", `12`="bilateral in one session", `21`="bilateral in one session", `23`="bilateral in one session", `32`="bilateral in one session", `13`="opposite lateralisations", `31`="opposite lateralisations")
# Main plot
pmain <- ggplot(myA2_right2, aes(x = Jabber1, y = Jabber2, color = Jabber12))+
  geom_point()+ggpubr::color_palette("jco")+annotate('text',2,-2,label=paste0('r = ',round(cor(myA2_right$Jabber1,myA2_right$Jabber2,use='complete.obs'),2)))+theme_bw() + guides(color=guide_legend(title="Laterality class"))+ rremove("legend") 
# Marginal densities along x axis
xdens <- axis_canvas(pmain, axis = "x")+
  geom_density(data = myA2_right2, aes(x = Jabber1, fill = Jabber12),
               alpha = 0.7, size = 0.2)+
  ggpubr::fill_palette("jco")
# Marginal densities along y axis
# Need to set coord_flip = TRUE, if you plan to use coord_flip()
ydens <- axis_canvas(pmain, axis = "y", coord_flip = TRUE)+
  geom_density(data = myA2_right2, aes(x = Jabber2, fill = Jabber12),
               alpha = 0.7, size = 0.2)+
  coord_flip()+
  ggpubr::fill_palette("jco")
p1 <- insert_xaxis_grob(pmain, xdens, grid::unit(.2, "null"), position = "top")
p2<- insert_yaxis_grob(p1, ydens, grid::unit(.2, "null"), position = "right")
g2<-ggdraw(p2)
```


```{r plot_both}
ggarrange(g1,g2,ncol=2,nrow=1,labels=c('LEFT','RIGHT'))
```